### ISSUE TITLE
NameError: name 'pgn_source_url' is not defined

### ISSUE THREAD

**Issue by fredjust** [lakinwecker/pgnstudyrelay#20]
File "C:\Python\pgnstudyrelay\pgnstudyrelay.py", line 235 , in main
    print("Polling URL: {}".format(pgn_source_url))
NameError: name 'pgn_source_url' is not defined

**Comment by fredjust** [comment]
I change the ligne by
print("Polling URL: {}".format(url))

**Comment by lakinwecker** [comment]
Same here. This isn't my latest code. Fix pushed.

**Comment by fredjust** [comment]
THANKS it's work now
I continue my tests
