### ISSUE TITLE
NameError: name 'self' is not defined line 191

### ISSUE THREAD

**Issue by fredjust** [lakinwecker/pgnstudyrelay#22]
File "C:\Python\pgnstudyrelay\pgnstudyrelay.py", line 191
, in poll_url
    response = await self.lichess.session.get(url)
NameError: name 'self' is not defined

**Comment by lakinwecker** [comment]
Sorry. I hadn't pushed my latest code. I think this is fixed in it.

**Comment by fredjust** [comment]
THANKS it's work now
I continue my tests
