### ISSUE TITLE
1/2-1/2 is added when I import the PGN to start with

### ISSUE THREAD

**Issue by lakinwecker** [lakinwecker/pgnstudyrelay#4]
Unsure why. The result is `*`. Not sure if this is a bug in what I'm doing or the studies.

**Comment by ornicar** [comment]
That should fix it https://github.com/ornicar/lila/commit/dedea4c94c42725e7772be5dc0d80e1314db3086

**Comment by lakinwecker** [comment]
Yup, fixed on stage, thanks!
