### ISSUE TITLE
Add result when the result is finally added.

### ISSUE THREAD

**Issue by lakinwecker** [lakinwecker/pgnstudyrelay#5]
When the result is finally added, we should detect it and add the result ourselves. Probably requires fixing #4 first.

**Comment by ornicar** [comment]
You can comment nodes with the WS API, and set PGN tags too. Inspect the frames.

**Comment by lakinwecker** [comment]
Yeah, I just didn't realize the result was a comment. 👍

**Comment by lakinwecker** [comment]
Done!  The result tag doesn't update live on stage. A reload is required.
