### ISSUE TITLE
Deal with situations where the study PGN is longer than our PGN. 

### ISSUE THREAD

**Issue by lakinwecker** [lakinwecker/pgnstudyrelay#6]
Unsure what to do in that situation.

**Comment by ornicar** [comment]
append your move at its path, and promote it to mainline.

**Comment by lakinwecker** [comment]
I will also have to detect if the move that I want to append is part of the non-mainline variations. So I guess I do have to properly parse the tree

**Comment by lakinwecker** [comment]
https://github.com/ornicar/lila/commit/87777f288a12136484dcb642fd70588d2476a11d

Solve by using the new 'promote: true' option with anaMove. thanks @ornicar!
