### ISSUE TITLE
Add times when adding moves

### ISSUE THREAD

**Issue by lakinwecker** [lakinwecker/pgnstudyrelay#7]
When a PGN is imported, the `clk` values are used to show times. When `anaMove` is sent, it's unclear to me if I can send the same `clk` values with it?

**Comment by ornicar** [comment]
https://github.com/ornicar/lila/commit/dfb2612700ac0cf6e9354c1ee2d128dcc2a14ce6

**Comment by ornicar** [comment]
```
{
  clock: 360000 // centis
  clock: '01:00:00' // or HH:MM:SS
}
```

**Comment by lakinwecker** [comment]
I am now sending these on stage, but they aren't showing up.

**Comment by lakinwecker** [comment]
Ok, closing for now. We can deal with any bugs in a different ticket. Thanks @ornicar !
